services:
  optimizer:
    image: optimizer
    ports:
      - ${OPTIMIZER_HOST_PORT}:${OPTIMIZER_CONTAINER_PORT}
    environment:
      - EIKON_APP_KEY=${EIKON_APP_KEY}
      - JUSTETF_URL=${JUSTETF_URL}
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_DB_PORT=${MONGO_DB_CONTAINER_PORT}
      - OPTIMIZER_CONTAINER_PORT=${OPTIMIZER_CONTAINER_PORT}
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - ${MONGO_DB_HOST_PORT}:${MONGO_DB_CONTAINER_PORT}
    volumes:
      - ${MONGO_DB_DATA_LOCATION}:/data/db