version: "3"
services:
  frontend:
    image: manuelmanso/etfoptimizer:frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - /home/ubuntu/ssl:/etc/nginx/certs
    depends_on:
      - optimizer

  optimizer:
    image: manuelmanso/etfoptimizer:optimizer
    restart: always
    build:
      context: ./src
      dockerfile: Dockerfile
    expose:
      - 8080
    volumes:
      - ./src:/usr/src/app
    environment:
      - MONGO_DB_HOST=${MONGO_DB_HOST}