version: "3"
services:
  frontend:
    image: gcr.io/etfoptimizer/frontend:v1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - /home/ubuntu/ssl:/etc/nginx/certs
    depends_on:
      - optimizer-service

  optimizer-service:
    image: gcr.io/etfoptimizer/optimizer:v1
    restart: always
    build:
      context: ./src
      dockerfile: Dockerfile
    expose:
      - 8080
    volumes:
      - ./src:/usr/src/app
    environment:
      - MONGO_DB_HOST=mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 2717:27017
    volumes:
      - etfData:/data/db

volumes:
  etfData: {}