apiVersion: apps/v1

kind: Deployment

metadata:
  name: frontend-deployment
  labels:
    app: frontend-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      name: frontend
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: gcr.io/etfoptimizer/frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80