apiVersion: apps/v1

kind: Deployment

metadata:
  name: frontend-deployment
  labels:
    app: frontend-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      name: frontend
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: manuelmanso/etfoptimizer-frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---

apiVersion: v1

kind: Service

metadata:
  name: frontend-service
  labels:
    app: frontend-service

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: frontend