apiVersion: v1
kind: Service
metadata:
  name: optimizer-service
  labels:
    app: optimizer-service

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: optimizer