apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimizer-deployment
  labels:
    app: optimizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optimizer
  template:
    metadata:
      labels:
        app: optimizer
    spec:
      containers:
        - name: optimizer
          image: manuelmanso/etfoptimizer-optimizer:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: optimizer-service
  labels:
    app: optimizer-service

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: optimizer